# Firmus Linux neofetch configuration

print_info() {
    info title
    info underline

    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
    info "Disk" disk
    info "Init" init

    info line_break
    info cols
    info line_break
}

# Enable/disable color blocks
color_blocks="on"
bold="on"

# Image backend
image_backend="ascii"

# ASCII art
ascii_distro="auto"
ascii_colors=(6 7 8)
