#!/usr/bin/env bash
# Firmus Linux — TCR package test script
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
PKG_DIR="$PROJECT_DIR/packages/tcr"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${CYAN}[INFO]${NC} $*"; }
log_ok() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

PASS=0
FAIL=0

check_pkgbuild() {
    local pkg="$1"
    local pkgbuild="$PKG_DIR/$pkg/PKGBUILD"

    if [ ! -f "$pkgbuild" ]; then
        log_error "Missing PKGBUILD: $pkg"
        return 1
    fi

    if ! grep -q "^pkgname=" "$pkgbuild"; then
        log_error "PKGBUILD '$pkg' missing pkgname"
        return 1
    fi

    if ! grep -q "^pkgver=" "$pkgbuild"; then
        log_error "PKGBUILD '$pkg' missing pkgver"
        return 1
    fi

    if ! grep -q "^pkgdesc=" "$pkgbuild"; then
        log_error "PKGBUILD '$pkg' missing pkgdesc"
        return 1
    fi

    return 0
}

check_srcinfo() {
    local pkg="$1"
    local srcinfo="$PKG_DIR/$pkg/.SRCINFO"

    if [ ! -f "$srcinfo" ]; then
        log_warn "No .SRCINFO for '$pkg' (generated by makepkg)"
    fi
}

check_license() {
    local pkg="$1"
    local pkgbuild="$PKG_DIR/$pkg/PKGBUILD"

    if [ -f "$pkgbuild" ] && ! grep -q "^license=" "$pkgbuild"; then
        log_warn "PKGBUILD '$pkg' missing license field"
    fi
}

test_package() {
    local pkg="$1"
    log_info "Testing '$pkg'..."

    if check_pkgbuild "$pkg"; then
        check_srcinfo "$pkg"
        check_license "$pkg"
        log_ok "'$pkg' passed"
        PASS=$((PASS + 1))
    else
        FAIL=$((FAIL + 1))
    fi
}

test_tier() {
    local tier_file="$1"
    local tier_name="$2"

    if [ ! -f "$tier_file" ]; then
        log_warn "Tier file not found: $tier_file"
        return
    fi

    log_info "Testing $tier_name..."

    while IFS= read -r line; do
        line=$(echo "$line" | xargs)
        [ -z "$line" ] && continue
        [[ "$line" =~ ^# ]] && continue
        test_package "$line"
    done < "$tier_file"
}

main() {
    echo "========================================"
    echo "  Firmus Linux — Package Tests"
    echo "========================================"
    echo ""

    test_tier "$PKG_DIR/tier1.csv" "Tier 1 (Core)"
    test_tier "$PKG_DIR/tier2.csv" "Tier 2 (Community)"
    test_tier "$PKG_DIR/tier3.csv" "Tier 3 (Binary Cache)"

    echo ""
    echo "========================================"
    echo "  Results: $PASS passed, $FAIL failed"
    echo "========================================"

    exit $FAIL
}

main "$@"
