# Firmus Linux /etc/pacman.conf

[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 10
ILoveCandy
VerbosePkgLists

# Firmus Trusted Community Repository
[firmus]
SigLevel = Required TrustedOnly
Server = https://firmuslinux.github.io/firmuslinux/x86_64

# Official repositories
[core]
SigLevel = Required DatabaseOptional
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = Required DatabaseOptional
Include = /etc/pacman.d/mirrorlist

[multilib]
SigLevel = Required DatabaseOptional
Include = /etc/pacman.d/mirrorlist
