# Firmus Linux NetworkManager configuration
[main]
plugins=keyfile
dhcp=internal

[connectivity]
uri=http://connectivity-check.firmuslinux.org
interval=300

[device]
wifi.backend=iwd
wifi.scan-rand-mac-address=yes
