# Firmus Linux dracut defaults
hostonly=yes
hostonly_cmdline=yes
compress="zstd"
compress_args="-1"
add_dracutmodules+=" btrfs snapper lvm dm dmraid crypt mdraid "
add_dracutmodules+=" nfs network kernel-modules "
add_drivers+=" btrfs ext4 xfs vfat nls_iso8859-1 nls_utf8 "
add_firmware+=" yes "
uefi=yes
uefi_stub="/usr/lib/systemd/boot/efi/linuxx64.efi.stub"
uefi_output_dir="/boot/EFI/Linux/"
generate_standalone_initramfs=yes
