# Firmus Linux Calamares configuration

modules-search: [ local ]

instances:
    - id:       firmus_nvidia
      module:   shellprocess
      config:   firmus-nvidia.conf
    - id:       firmus_seat
      module:   shellprocess
      config:   firmus-seat.conf
    - id:       firmus_snapper
      module:   shellprocess
      config:   firmus-snapper.conf
    - id:       firmus_bootloader
      module:   shellprocess
      config:   firmus-bootloader.conf
    - id:       firmus_tcr
      module:   shellprocess
      config:   firmus-tcr.conf
    - id:       firmus_desktop
      module:   shellprocess
      config:   firmus-desktop.conf

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - summary
    - exec:
        - partition
        - mount
        - unpackfs
        - machineid
        - fstab
        - locale
        - keyboard
        - localecfg
        - luksopenswaphookcfg
        - luksbootkeyfile
        - plymouthcfg
        - initcpiocfg
        - initcpio
        - users
        - displaymanager
        - networkcfg
        - hwclock
        - services
        - grubcfg
        - bootloader
        - firmus_nvidia
        - firmus_seat
        - firmus_snapper
        - firmus_bootloader
        - firmus_tcr
        - firmus_desktop
        - postcfg
        - umount
    - show:
        - finished

branding: firmus

dont-chroot: false
oem-setup: false
preserve-fstab: true
